### ISSUE TITLE
Doesn't work in Galaxy S23

### ISSUE THREAD

**Issue by DorH92** [C0ntrolDev/spotify_downloader#11]
The app crashes even in the first running..

**Comment by C0ntrolDev** [comment]
What version of android do you have?
And if you can, please provide additional information

**Comment by DorHadar** [comment]
@C0ntrolDev 

Android 14.

The only information I have is that it just crashes when while initializing..

**Comment by C0ntrolDev** [comment]
Sorry, I haven't tested the work on Android 14, only on Android 13. 

I think it might be related to one of the libraries (flutter_background). I'll check it as soon as possible.

**Comment by DorHadar** [comment]
@C0ntrolDev 

Ok.
The app supports automatic download when new track added to a playlist?

**Comment by C0ntrolDev** [comment]
No.
I don't think it's even possible to do that. But the idea is interesting. For now you can just click the "Download all" button on the playlist page. It will only download what hasn't been downloaded.

**Comment by C0ntrolDev** [comment]
Hi, I think I fixed the problem. Download apk from this link.
https://drive.google.com/file/d/1dRTSejrN9i3OPWYMzDk1eRezLoOGBwqt/view?usp=drivesdk

**Comment by extraut** [comment]
![efaa85262c2979c0bce49d0dc643d49e](https://github.com/user-attachments/assets/2d3295e5-f6ed-4d1d-93a8-15e6366828b6)

**Comment by C0ntrolDev** [comment]
Can I close the Issue?

**Comment by DorHadar** [comment]
I didn't try that yet. But if you say it's been solved so you probably know that..

**Comment by C0ntrolDev** [comment]
I'll wait until you make sure that the app works.

**Comment by DorHadar** [comment]
@C0ntrolDev 

The app works.

**Comment by Ryuza8i** [comment]
![photo_2024-10-31_04-39-09](https://github.com/user-attachments/assets/75a0b871-8d9b-4331-a63f-c8bec3a90da1)
i can 't install song i have iphone 12
