### ISSUE TITLE
Not loading account content 

### ISSUE THREAD

**Issue by Pnu-kun** [C0ntrolDev/spotify_downloader#16]
Failure: "#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleErrors (package:spotify/src/spotify_base.dart:232)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:178)
<asynchronous suspension>
#9      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#10     SpotifyProfileDataSource.getSpotifyProfile.<anonymous closure> (package:spotify_downloader/features/data_domain/spotify_profile/data/data_source/spotify_profile_data_source.dart:10)
<asynchronous suspension>
#11     handleSpotifyClientExceptions (package:spotify_downloader/core/utils/util_methods.dart:20)
<asynchronous suspension>
#12     SpotifyProfileRepositoryImpl.getSpotifyProfile (package:spotify_downloader/features/data_domain/spotify_profile/data/repository/spotify_profile_repository_impl.dart:14)
<asynchronous suspension>
#13     AccountAuthBloc._onUpdate (package:spotify_downloader/features/presentation/settings/widgets/auth_settings/blocs/account_auth/account_auth_bloc.dart:53)
<asynchronous suspension>
#14     new AccountAuthBloc.<anonymous closure> (package:spotify_downloader/features/presentation/settings/widgets/auth_settings/blocs/account_auth/account_auth_bloc.dart:28)
<asynchronous suspension>
#15     Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:229)
<asynchronous suspension>
"  FormatException: Unexpected character (at character 1)
Check settings on developer.spotify.com/dashboard, the user may not be regi...
^

**Comment by C0ntrolDev** [comment]
Hello, did you change the client_id and client_secret in the app settings?

**Comment by Pnu-kun** [comment]
NO all I did was login to my Spotify account

**Comment by C0ntrolDev** [comment]
In my app, account login is only needed to download your favorite tracks, and to properly display “only for you” playlists. 
If you want any of these, you'll need to create a Spotify Service App to do so. Instructions are in the [documentation](https://github.com/C0ntrolDev/spotify_downloader?tab=readme-ov-file#how-create-spotify-service-app-and-use-it)

**Comment by C0ntrolDev** [comment]
Can i lose the issue?

**Comment by Pnu-kun** [comment]
Yes, please!
