### ISSUE TITLE
Downloading error : Failure

### ISSUE THREAD

**Issue by Doblequeso** [C0ntrolDev/spotify_downloader#19]
This error   shows on every song i try to download  
i created  my Spotify Service App  and everything went  ok , until  i start downloading my  liked songs  then the error  showed up on every song 

Download error  : Failure_ "null" Video  

this is the error log 

Failure: "null"  VideoUnavailableException: Video '6BCld5HWUZ0' is unavailable
In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
Please report this issue on GitHub in that case.

**Comment by C0ntrolDev** [comment]
Hi, I may have fixed your problem, check it out
https://drive.google.com/file/d/1olM1WnGogj47OSpHjV0kJofVEAbrnSHb/view

**Comment by Doblequeso** [comment]
It worked  thank you so much! ✨🤞
