### ISSUE TITLE
Баг с  невозможностью скачивания 

### ISSUE THREAD

**Issue by RocetDev** [C0ntrolDev/spotify_downloader#6]
Привет! У меня и у друга возникла проблема. Ошибка: PathAccessException: Creation failed, path = '/storage/emulated/0/Music/_AllTracks' (OS Error: Permission denied, error = 13) Доступ к хранилищу приложению разрешил.

Android 10 QKQ1.190910.002

**Comment by C0ntrolDev** [comment]
Привет, вроде исправил баг, проверь на работоспособность
[app-armeabi-v7a-release.zip](https://github.com/C0ntrolDev/spotify_downloader/files/13986104/app-armeabi-v7a-release.zip)

**Comment by RocetDev** [comment]
Спасибо большое
